---
title: "Bamboo mesocosms experiment"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
 rmarkdown::html_document:
    theme: cerulean
    toc: yes
    toc_float: yes
    highlight: haddock
    number_sections: true
editor_options: 
  chunk_output_type: console
---

# Setup

## Libs

```{r}
#install.packages("remotes")
#install.packages('TMB',source=TRUE) #didn't work on home laptop
#remotes::install_github("glmmTMB/glmmTMB/glmmTMB")
library("glmmTMB")
#install.packages("BiocManager")
#BiocManager::install("phyloseq")
library("phyloseq")
library("dplyr")
# #install.packages("reshape")
library("reshape")
# library("ggplot2")
# #install.packages("bbmle")
library("bbmle")
# #install.packages("car")
# library("car")
library("DHARMa")
library("plyr")
library("ggplot2")
```

## Re-read data

```{r}
setwd("~/nicolagk@hawaii.edu - Google Drive/My Drive/Bamboo_mesos/Bamboo_mesos/04.mixed_models/")

ps.clean <- readRDS("../01.process_asvs/bamboomesos_ps.lulu.clean.decontam.rds")
ps.clean #514 taxa, 169 samples

ps.exp.all <- subset_samples(ps.clean,Mesocosm_type=="Experiment"&Microbe_treatment!="AHK"&Exp_day!=20)
ps.exp.all #100 samples

##water samples
ps.exp.all.wtr <- subset_samples(ps.exp.all,Sample_type=="Water")
ps.exp.all.wtr #50 samples

##larvae samples
ps.exp.all.lar <- subset_samples(ps.exp.all,Sample_type=="Larvae")
ps.exp.all.lar #50 samples
```

# Data formatting

## Trim, thoroughly

Ran once then saved

```{r}
##6 samples out of 50 = 12%

ps.exp.all.wtr.trim <- filter_taxa(ps.exp.all.wtr, function(x) sum(x > 1) > (0.12*length(x)), TRUE)
ps.exp.all.wtr.trim #69 taxa

ps.exp.all.lar.trim <- filter_taxa(ps.exp.all.lar, function(x) sum(x > 1) > (0.12*length(x)), TRUE)
ps.exp.all.lar.trim #54 taxa

##proportion of zeroes
##water - with all
otu.exp.all.wtr <- data.frame(ps.exp.all.wtr@otu_table)
sum(otu.exp.all.wtr == 0) / (ncol(otu.exp.all.wtr) * nrow(otu.exp.all.wtr)) * 100
#94.27237%
 
otu.exp.all.wtr.trim <- data.frame(ps.exp.all.wtr.trim@otu_table)
sum(otu.exp.all.wtr.trim == 0) / (ncol(otu.exp.all.wtr.trim) * nrow(otu.exp.all.wtr.trim)) * 100
#64.11594%

##save if ready
#saveRDS(ps.exp.wtr.trim,file="ps.exp.wtr.trim.rds")
#saveRDS(ps.exp.all.wtr.trim,file="ps.exp.all.wtr.trim.rds")

##larvae - with all
otu.exp.all.lar <- data.frame(ps.exp.all.lar@otu_table)
sum(otu.exp.all.lar == 0) / (ncol(otu.exp.all.lar) * nrow(otu.exp.all.lar)) * 100
#95.96498%
 
otu.exp.all.lar.trim <- data.frame(ps.exp.all.lar.trim@otu_table)
sum(otu.exp.all.lar.trim == 0) / (ncol(otu.exp.all.lar.trim) * nrow(otu.exp.all.lar.trim)) * 100
#70.96296%

##save if ready
#saveRDS(ps.exp.lar.trim,file="ps.exp.lar.trim.rds")
#saveRDS(ps.exp.all.lar.trim,file="ps.exp.all.lar.trim.rds")
```

## More formatting - long form

```{r}
otu.all.wtr <- data.frame(ps.exp.all.wtr.trim@otu_table)
otu.all.lar <- data.frame(ps.exp.all.lar.trim@otu_table)

#total read count colums
otu.all.wtr$sum <- rowSums(otu.all.wtr)
otu.all.lar$sum <- rowSums(otu.all.lar)

otu.all.wtr$Short_label <- row.names(otu.all.wtr)
otu.all.lar$Short_label <- row.names(otu.all.lar)

#bring in the metadata again
samdf.all.wtr <- data.frame(ps.exp.all.wtr.trim@sam_data)
samdf.all.lar <- data.frame(ps.exp.all.lar.trim@sam_data)

##add extra metadata
#meso.data <- read.csv("../bamboomesos_metadata.csv")

#samdf.wtr.more <- merge(samdf.wtr,meso.data)
#samdf.lar.more <- merge(samdf.lar,meso.data)

#samdf.wtr$food.microbes <- paste0(samdf.wtr$Food_type,"_",samdf.wtr$Microbe_treatment)
#samdf.lar$food.microbes <- paste0(samdf.lar$Food_type,"_",samdf.lar$Microbe_treatment)
# 
# #join the data sets by sample name
df.all.water <- plyr::join(otu.all.wtr, samdf.all.wtr, by="Short_label", type="left")
df.all.larv <- plyr::join(otu.all.lar, samdf.all.lar, by="Short_label", type="left")
colnames(df.all.water)

##getting rid of some irrelevant metadat
df.all.water1 <- df.all.water %>%
  dplyr::select(-Short_label,-Longer_name,-Sample_type,-Num_larvae,-Date_collected,-Exp_day,-Mesocosm_treatment,-Mesocosm_type,-Treatment_notes,-Notes,-Raw_reads,-Num_larvae_d00,-Num_larvae_d08,-Num_larvae_d34,-Num_larvae_d40,-Total_pupae,-Proportion_pupated,-Biomass_day30,-lib_size_clean,-is.neg)
colnames(df.all.water1)

df.all.water.long <- melt(df.all.water1, id.vars=c("sum", "Mesocosm_id", "Microbe_treatment","Food_type", "Biomass_day40"))

df.all.water.long$rowid <- 1:nrow(df.all.water.long)

df.all.larv1 <- df.all.larv %>%
  dplyr::select(-Short_label,-Longer_name,-Sample_type,-Num_larvae,-Date_collected,-Exp_day,-Mesocosm_treatment,-Mesocosm_type,-Treatment_notes,-Notes,-Raw_reads,-Num_larvae_d00,-Num_larvae_d08,-Num_larvae_d34,-Num_larvae_d40,-Total_pupae,-Proportion_pupated,-Biomass_day30,-lib_size_clean,-is.neg)
colnames(df.all.larv1)

#df.all.larv2 <- df.all.larv1[df.all.larv1$sum!=0,]
#df.all.larv2$sum==0

df.all.larv.long <- melt(df.all.larv1, id.vars=c("sum", "Mesocosm_id", "Microbe_treatment","Food_type", "Biomass_day40"))

df.all.larv.long$rowid <- 1:nrow(df.all.larv.long)

##save
#saveRDS(df.all.water.long,file="df.all.water.long.rds")
#saveRDS(df.all.larv.long,file="df.all.larv.long.rds")
```

# Running the statz

Can start from here

```{r}
setwd("~/nicolagk@hawaii.edu - Google Drive/My Drive/Bamboo_mesos/Bamboo_mesos/04.mixed_models")

df.all.water.long <- readRDS("df.all.water.long.rds")
df.all.larv.long <- readRDS("df.all.larv.long.rds")
```

## 2-way interactions

### Just larvae first

```{r}
df.all.larv.long <- readRDS("df.all.larv.long.rds")

str(df.all.larv.long)
df.all.larv.long$rowid <- as.factor(df.all.larv.long$rowid)
df.all.larv.long$Microbe_treatment <- as.factor(df.all.larv.long$Microbe_treatment)
df.all.larv.long$Food_type <- as.factor(df.all.larv.long$Food_type)
#df.all.larv.long$food.microbes <- as.factor(df.all.larv.long$food.microbes)
df.all.larv.long$Mesocosm_id <- as.factor(df.all.larv.long$Mesocosm_id)
str(df.all.larv.long)

##binomial
#larv.mod.bin <- glmmTMB(cbind(value, sum-value)~Microbe_treatment*Food_type+(1|variable)+(1|variable:Microbe_treatment)+(1|variable:Food_type)+(1|variable:Microbe_treatment:Food_type)+(1|rowid),family=binomial,data=df.all.larv.long)
#summary(larv.mod.bin)

##full model
# larv.mod.nb1 <- glmmTMB(value~offset(log(sum))+Microbe_treatment+Food_type+(1|variable)+(1|variable:Microbe_treatment)+(1|variable:Food_type)+(1|variable:Microbe_treatment:Food_type),disp=~variable+Food_type+Microbe_treatment,family=nbinom1,data=df.all.larv.long)
# summary(larv.mod.nb1)

larv.mod.nb1 <- glmmTMB(value~offset(log(sum))+Microbe_treatment+Food_type+(1|variable)+(1|variable:Microbe_treatment)+(1|variable:Food_type),family=nbinom1,data=df.all.larv.long)
summary(larv.mod.nb1)

larv.mod.nb2 <- glmmTMB(value~offset(log(sum))+Microbe_treatment+Food_type+(1|variable)+(1|variable:Microbe_treatment)+(1|variable:Food_type),family=nbinom2,data=df.all.larv.long)
summary(larv.mod.nb2)

AICtab(larv.mod.nb1,larv.mod.nb2)

#larv.mod.bin.resid <- simulateResiduals(fittedModel = larv.mod.bin, plot = T)
#larv.mod.nb1.resid <- simulateResiduals(fittedModel = larv.mod.nb1, plot = T)
#larv.mod.nb2.resid <- simulateResiduals(fittedModel = larv.mod.nb2, plot = T)

##removing 2 way interactions
larv.mod.nb1.nomicr <- update(larv.mod.nb1,.~.-(1|variable:Microbe_treatment))
summary(larv.mod.nb1.nomicr)
anova(larv.mod.nb1,larv.mod.nb1.nomicr) #sig ***

larv.mod.nb1.nofood <- update(larv.mod.nb1,.~.-(1|variable:Food_type))
summary(larv.mod.nb1.nofood)
anova(larv.mod.nb1,larv.mod.nb1.nofood) #sig **

larv.mod.ranef.2ways <- as.data.frame(ranef(larv.mod.nb1))
#larv.mod.ranef.2ways
#write.csv(larv.mod.ranef.2ways,file="larv.mod.ranef.2ways.csv")
```

### Water

```{r}
df.all.water.long <- readRDS("df.all.water.long.rds")

str(df.all.water.long)
df.all.water.long$rowid <- as.factor(df.all.water.long$rowid)
df.all.water.long$Microbe_treatment <- as.factor(df.all.water.long$Microbe_treatment)
df.all.water.long$Food_type <- as.factor(df.all.water.long$Food_type)
#df.all.water.long$food.microbes <- as.factor(df.all.water.long$food.microbes)
df.all.water.long$Mesocosm_id <- as.factor(df.all.water.long$Mesocosm_id)
str(df.all.water.long)

##binomial
#water.mod.bin <- glmmTMB(cbind(value, sum-value)~Microbe_treatment*Food_type+(1|variable)+(1|variable:Microbe_treatment)+(1|variable:Food_type)+(1|variable:Microbe_treatment:Food_type)+(1|rowid),family=binomial,data=df.all.water.long)
#summary(water.mod.bin)

##full model
# water.mod.nb1 <- glmmTMB(value~offset(log(sum))+Microbe_treatment+Food_type+(1|variable)+(1|variable:Microbe_treatment)+(1|variable:Food_type)+(1|variable:Microbe_treatment:Food_type),disp=~variable+Food_type+Microbe_treatment,family=nbinom1,data=df.all.water.long)
# summary(water.mod.nb1)

water.mod.nb1 <- glmmTMB(value~offset(log(sum))+Microbe_treatment+Food_type+(1|variable)+(1|variable:Microbe_treatment)+(1|variable:Food_type),family=nbinom1,data=df.all.water.long)
summary(water.mod.nb1)

water.mod.nb2 <- glmmTMB(value~offset(log(sum))+Microbe_treatment+Food_type+(1|variable)+(1|variable:Microbe_treatment)+(1|variable:Food_type),family=nbinom2,data=df.all.water.long)
summary(water.mod.nb2)

AICtab(water.mod.nb1,water.mod.nb2)

#water.mod.bin.resid <- simulateResiduals(fittedModel = water.mod.bin, plot = T)
#water.mod.nb1.resid <- simulateResiduals(fittedModel = water.mod.nb1, plot = T)
#water.mod.nb2.resid <- simulateResiduals(fittedModel = water.mod.nb2, plot = T)

##removing 2 way interactions
water.mod.nb1.nomicr <- update(water.mod.nb1,.~.-(1|variable:Microbe_treatment))
summary(water.mod.nb1.nomicr)
anova(water.mod.nb1,water.mod.nb1.nomicr) #sig ***

water.mod.nb1.nofood <- update(water.mod.nb1,.~.-(1|variable:Food_type))
summary(water.mod.nb1.nofood)
anova(water.mod.nb1,water.mod.nb1.nofood) #sig **

water.mod.ranef.2ways <- as.data.frame(ranef(water.mod.nb1))
#water.mod.ranef.2ways
#write.csv(water.mod.ranef.2ways,file="water.mod.ranef.2ways.csv")

```
